aws_region             = "us-west-2"
enable_control_tower   = true
master_account_email   = "lets.talk.about.2023@gmail.com"
master_account_id      = "863518414447"
dev_account_email      = "dev+lets.talk.about.2023@gmail.com"
prod_account_email     = "prod+lets.talk.about.2023@gmail.com"
shared_account_email   = "shared+lets.talk.about.2023@gmail.com"
security_account_email = "security+lets.talk.about.2023@gmail.com"
audit_account_email    = "audit+lets.talk.about.2023@gmail.com"
aft_logs_bucket_name   = "aft-logs-bucket-863518414447"
organizational_units   = ["Security", "Audit Log", "Sandbox"]
